apiVersion: v1
kind: Service
metadata:
  name: web-application
  labels:
    app: web-application
spec:
  selector:
    app: web-application
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP # Use ClusterIP for internal access, or LoadBalancer for external access